Project_63135935/Project_63135935/Areas/Admin/Controllers/AdminKhachHangs_63135935Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63135935.Models;

namespace Project_63135935.Areas.Admin.Controllers
{
    public class AdminKhachHangs_63135935Controller : Controller
    {
        private Project_63135935Entities1 db = new Project_63135935Entities1();

        // GET: Admin/AdminKhachHangs_63135935

        string LayMaKh()
        {
            var maMax = db.KhachHangs.Select(n => n.MaKH).OrderByDescending(ma => ma).FirstOrDefault();

            if (maMax != null)
            {
                int maSach = int.Parse(maMax.Substring(3)) + 1;
                string newMaSach = "MKH" + maSach.ToString("000");
                return newMaSach;
            }

            return "MKH001";
        }

        public ActionResult Index()
        {
            return View(db.KhachHangs.ToList());
        }

        [HttpPost]
        public ActionResult Index(string tenKH)
        {
            var tenkh = db.KhachHangs.Where(s => s.TenKH.Contains(tenKH)).ToList();
            return View(tenkh);
        }

        // GET: Admin/AdminKhachHangs_63135935/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // GET: Admin/AdminKhachHangs_63135935/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminKhachHangs_63135935/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKH,HoKH,TenKH,DiaChi,SoDT,NgaySinh,GioiTinh,Email,Matkhau")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                khachHang.MaKH = LayMaKh();
                db.KhachHangs.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Index", "Login_63135935");
            }

            return View(khachHang);
        }

        // GET: Admin/AdminKhachHangs_63135935/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: Admin/AdminKhachHangs_63135935/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKH,HoKH,TenKH,DiaChi,SoDT,NgaySinh,GioiTinh,Email,Matkhau")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khachHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khachHang);
        }

        // GET: Admin/AdminKhachHangs_63135935/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: Admin/AdminKhachHangs_63135935/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            KhachHang khachHang = db.KhachHangs.Find(id);
            db.KhachHangs.Remove(khachHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_63135935/Project_63135935/Areas/Admin/Views/AdminKhachHangs_63135935/Create.cshtml
@model Project_63135935.Models.KhachHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Register.cshtml";
}

<div class="p-5">
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
    </div>
    @using (Html.BeginForm("Create", "AdminKhachHangs_63135935", FormMethod.Post, new { enctype = "multipart/form-data", @class = "user" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                @Html.EditorFor(model => model.HoKH, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Họ Người Dùng" } })
                @Html.ValidationMessageFor(model => model.HoKH, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-6">
                @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Tên Người Dùng" } })
                @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group d-flex">
            @Html.LabelFor(model => model.GioiTinh, "Giới Tính:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>
        <div class="form-group">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control form-control-user", @type = "email", placeholder = "Email Đăng Nhập" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Địa Chỉ" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
        <div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Số Điện Thoại" } })
                @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-6">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Ngày Sinh" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.EditorFor(model => model.Matkhau, new { htmlAttributes = new { @class = "form-control form-control-user", @type = "password", placeholder = "Mật Khẩu" } })
            @Html.ValidationMessageFor(model => model.Matkhau, "", new { @class = "text-danger" })
        </div>
        <input value="Register Account" type="submit" class="btn btn-primary btn-user btn-block" />
        <hr>
    }

    <hr>
    <div class="text-center">
        <a class="small" href="@Url.Action("Index", "Login_63135935")">Already have an account? Login!</a>
    </div>
</div>

Project_63135935/Project_63135935/Areas/Admin/Views/AdminKhachHangs_63135935/Delete.cshtml
@model Project_63135935.Models.KhachHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var gtinh = "";
}

<style>
    .form-actions a {
        background-color: #4e73df;
        padding: 6px 12px;
    }
</style>

<div class="container-fluid">
    <h3 class="my-4">Bạn có chắc chắn xóa khách hàng này?</h3>

    <div style="font-size:18px; align-items: center" class="d-sm-block d-md-flex">
        <div>
            <table cellpadding="10">
                <tr>
                    <td>Mã Khách Hàng:</td>
                    <td>@Html.DisplayFor(model => model.MaKH)</td>
                <tr>
                    <td>Họ Khách Hàng:</td>
                    <td>@Html.DisplayFor(model => model.HoKH)</td>
                </tr>
                <tr>
                    <td>Tên Khách Hàng:</td>
                    <td>@Html.DisplayFor(model => model.TenKH)</td>
                </tr>
                <tr>
                    <td>Giới tính:</td>
                    <td>
                        @{if (Model.GioiTinh == true)
                            { gtinh = "Nam"; }
                            else
                            { gtinh = "Nữ"; }
                        }
                        @gtinh
                    </td>
                </tr>
                <tr>
                    <td>Số Điện Thoại:</td>
                    <td>@Html.DisplayFor(model => model.SoDT)</td>
                </tr>
                <tr>
                    <td>Ngày Sinh:</td>
                    <td>@Html.DisplayFor(model => model.NgaySinh)</td>
                </tr>
                <tr>
                    <td>Địa Chỉ:</td>
                    <td>@Html.DisplayFor(model => model.DiaChi)</td>
                </tr>
                <tr>
                    <td>Email Đăng Nhập:</td>
                    <td>@Html.DisplayFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td>Mật Khẩu:</td>
                    <td>@Html.DisplayFor(model => model.Matkhau)</td>
                </tr>
            </table>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions text-white d-sm-flex justify-content-center">
            <input type="submit" value="Delete" class="btn btn-default btn-primary" /> |
            @Html.ActionLink("Quay Lại", "Index")
        </div>
    }
</div>

Project_63135935/Project_63135935/Areas/Admin/Views/AdminKhachHangs_63135935/Details.cshtml
@model Project_63135935.Models.KhachHang

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var gtinh = "";
}

<style>
    p a {
        color: white;
        padding: 6px 12px;
        margin: 0px 5px;
        background-color: #4e73df;
    }
</style>

<div class="container-fluid">
    <h3 class="my-4">THÔNG TIN CHI TIẾT KHÁCH HÀNG</h3>

    <div style="font-size:18px; align-items: center" class="d-sm-block d-md-flex">
        <div>
            <table cellpadding="10">
                <tr>
                    <td>Mã Khách Hàng:</td>
                    <td>@Html.DisplayFor(model => model.MaKH)</td>
                <tr>
                    <td>Họ Khách Hàng:</td>
                    <td>@Html.DisplayFor(model => model.HoKH)</td>
                </tr>
                <tr>
                    <td>Tên Khách Hàng:</td>
                    <td>@Html.DisplayFor(model => model.TenKH)</td>
                </tr>
                <tr>
                    <td>Giới tính:</td>
                    <td>
                        @{if (Model.GioiTinh == true)
                            { gtinh = "Nam"; }
                            else
                            { gtinh = "Nữ"; }
                        }
                        @gtinh
                    </td>
                </tr>
                <tr>
                    <td>Số Điện Thoại:</td>
                    <td>@Html.DisplayFor(model => model.SoDT)</td>
                </tr>
                <tr>
                    <td>Ngày Sinh:</td>
                    <td>@Html.DisplayFor(model => model.NgaySinh)</td>
                </tr>
                <tr>
                    <td>Địa Chỉ:</td>
                    <td>@Html.DisplayFor(model => model.DiaChi)</td>
                </tr>
                <tr>
                    <td>Email Đăng Nhập:</td>
                    <td>@Html.DisplayFor(model => model.Email)</td>
                </tr>
                <tr>
                    <td>Mật Khẩu:</td>
                    <td>@Html.DisplayFor(model => model.Matkhau)</td>
                </tr>
            </table>
        </div>
    </div>
    <p class="my-4 d-sm-flex justify-content-center">
        @Html.ActionLink("Quay lại", "Index")
    </p>
</div>

Project_63135935/Project_63135935/Areas/Admin/Views/AdminKhachHangs_63135935/Edit.cshtml
@model Project_63135935.Models.KhachHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KhachHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKH)

        <div class="form-group">
            @Html.LabelFor(model => model.HoKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Matkhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matkhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matkhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_63135935/Project_63135935/Areas/Admin/Views/AdminKhachHangs_63135935/Index.cshtml
@model IEnumerable<Project_63135935.Models.KhachHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaKH", rowsPerPage: 10);
}

<head>
    <style>
        .btn_create {
            display: inline-block;
            max-width: 200px;
            background-color: lightskyblue;
            padding: 5px 10px;
            cursor: pointer;
        }

            .btn_create a {
                color: #4e73df !important;
                text-decoration: none;
            }

                .btn_create a:hover {
                    color: white !important;
                }

        a:hover, a {
            text-decoration: none !important;
        }

        form {
            display: flex !important;
            align-items: center;
            justify-content: center;
        }

        .btn-event {
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 10px 0px 20px 0px;
        }

        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue !important;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    color: #FFAD33;
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        table td {
            text-align: center;
        }

        th a {
            color: dodgerblue !important;
        }

        th {
            text-align: center;
        }

        .gridContent abbr[data-original-title], abbr[title] {
            cursor: pointer !important;
        }
    </style>
</head>

<body>

    <div class="container-fluid">
        <h2 style="text-align: center">DANH SÁCH KHÁCH HÀNG</h2>
        <div class="btn-event">

            @using (Html.BeginForm("Index", "AdminKhachHangs_63135935", FormMethod.Post, new { @class = "form-inline mr-auto ml-md-3 my-2 my-md-0 w-100 navbar-search" }))
            {
                @Html.AntiForgeryToken()
                <input type="text" name="tenKH" value="@ViewBag.tenKH" placeholder="search for..." class="form-control bg-light border-1 small w-50 mx-3" />
                <input type="submit" name="submit" value="tìm kiếm" style="background-color: blue;color:white" class="col-1" />
            }
        </div>

        <div id="gridContent">
            @ViewBag.TB
            @grid.GetHtml(
                tableStyle: "table table-bordered table-hover",
                footerStyle: "grid-footer",
                fillEmptyRows: true,
                mode: WebGridPagerModes.Numeric,
                alternatingRowStyle: "alternatingRowStyle",
                  columns: new[]  // colums in grid
                 {
            grid.Column("MaKH","Mã Khách Hàng"), //the model fields to display
            grid.Column("HoKH","Họ Khách Hàng"  ),
            grid.Column("TenKH","Tên Khách Hàng"),
            grid.Column("DiaChi","Địa Chỉ"),
            grid.Column("SoDT","Số Điện Thoại"),
grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
grid.Column("Email", "Email Đăng Nhập"),
grid.Column("Matkhau","Mật Khẩu"),
grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Details",
                    new { id = item.MaKH})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Delete",
                    new { id = item.MaKH})" class="edit-btn">
        <abbr title="Xóa dữ liệu">
            <img src="/images/delete.png" width="20" height="20" />
        </abbr>
    </a>
</text>),

}
)
        </div>
    </div>

</body>