Project_63135935/Project_63135935/Controllers/GioHangs_63135935Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63135935.Models;

namespace Project_63135935.Controllers
{
    public class GioHangs_63135935Controller : Controller
    {
        private Project_63135935Entities1 db = new Project_63135935Entities1();

        // GET: GioHangs_63135935

        string LayMaDH()
        {
            var maMax = db.GioHangs.Select(n => n.MaDH).OrderByDescending(ma => ma).FirstOrDefault();

            if (maMax != null)
            {
                int maSach = int.Parse(maMax.Substring(3)) + 1;
                string newMaSach = "MDH" + maSach.ToString("000");
                return newMaSach;
            }

            return "MDH001";
        }

        public ActionResult Index()
        {
            var gioHangs = db.GioHangs.Include(g => g.KhachHang).Include(g => g.NhanVien);
            return View(gioHangs.ToList());
        }

        // GET: GioHangs_63135935/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GioHang gioHang = db.GioHangs.Find(id);
            if (gioHang == null)
            {
                return HttpNotFound();
            }
            return View(gioHang);
        }

        // GET: GioHangs_63135935/Create
        public ActionResult Create(string idsach, string tensach)
        {
            // Lấy danh sách khách hàng và nhân viên từ cơ sở dữ liệu
            var khachHangs = db.KhachHangs.ToList();
            var nhanViens = db.NhanViens.ToList();
            ViewBag.idsach = tensach;

            // Tạo danh sách các mục chọn cho MaKH
            ViewBag.MaKH = new SelectList(khachHangs.Select(kh => new SelectListItem
            {
                Text = kh.HoKH + " " + kh.TenKH,
                Value = kh.MaKH.ToString()
            }), "Value", "Text");

            // Tạo danh sách các mục chọn cho MaNV
            ViewBag.MaNV = new SelectList(nhanViens.Select(nv => new SelectListItem
            {
                Text = nv.HoNV + " " + nv.TenNV,
                Value = nv.MaNV.ToString()
            }), "Value", "Text");

            return View();
        }


        // POST: GioHangs_63135935/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDH,NgayDat,MaKH,MaNV,Sodt,Diachigiaohang,Email,DuyetDH")] GioHang gioHang, string idsach)
        {
            var id = LayMaDH();

            if (ModelState.IsValid)
            {
                gioHang.MaDH = LayMaDH();
                gioHang.MaNV = "MNV003";
                gioHang.DuyetDH = false;
                gioHang.NgayDat = DateTime.Now;
                db.GioHangs.Add(gioHang);
                db.SaveChanges();
                return RedirectToAction("Create", "ChiTietGioHangs_63135935", new {idsach = idsach, idDH = id});
            }

            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoKH", gioHang.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "HoNV", gioHang.MaNV);
            return View(gioHang);
        }

        // GET: GioHangs_63135935/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GioHang gioHang = db.GioHangs.Find(id);
            if (gioHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoKH", gioHang.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "HoNV", gioHang.MaNV);
            return View(gioHang);
        }

        // POST: GioHangs_63135935/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDH,NgayDat,MaKH,MaNV,Sodt,Diachigiaohang,Email,DuyetDH")] GioHang gioHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gioHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoKH", gioHang.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "HoNV", gioHang.MaNV);
            return View(gioHang);
        }

        // GET: GioHangs_63135935/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GioHang gioHang = db.GioHangs.Find(id);
            if (gioHang == null)
            {
                return HttpNotFound();
            }
            return View(gioHang);
        }

        // POST: GioHangs_63135935/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            GioHang gioHang = db.GioHangs.Find(id);
            db.GioHangs.Remove(gioHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_63135935/Project_63135935/Controllers/Saches_63135935Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63135935.Models;

namespace Project_63135935.Controllers
{
    public class Saches_63135935Controller : Controller
    {
        private Project_63135935Entities1 db = new Project_63135935Entities1();

        // GET: Saches_63135935

        public ActionResult ShowBooksByCategory(string idcategory)
        {
            var bookincategory = db.Saches.SqlQuery("SELECT * FROM Sach WHERE MaLoaiSach='" + idcategory + "'");
            return View(bookincategory.ToList());
        }

        public ActionResult Aboutus()
        {
            var nhanviens = db.NhanViens.Include(n => n.Chucvu);
            return View(nhanviens);
        }

        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult Index()
        {
            var saches = db.Saches.Include(s => s.LoaiSach);
            return View(saches.ToList());
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            var saches = db.Saches.Where(s => s.TenSach.Contains(search)).ToList();
            return View(saches);
        }

        // GET: Saches_63135935/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // GET: Saches_63135935/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSach = new SelectList(db.LoaiSaches, "MaLoaiSach", "TenLoaiSach");
            return View();
        }

        // POST: Saches_63135935/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSach,MaLoaiSach,TenSach,AnhSach,DonGia,TacGia,NhaXuatBan,Mota,NgayXuatBan")] Sach sach)
        {
            if (ModelState.IsValid)
            {
                db.Saches.Add(sach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiSach = new SelectList(db.LoaiSaches, "MaLoaiSach", "TenLoaiSach", sach.MaLoaiSach);
            return View(sach);
        }

        // GET: Saches_63135935/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSach = new SelectList(db.LoaiSaches, "MaLoaiSach", "TenLoaiSach", sach.MaLoaiSach);
            return View(sach);
        }

        // POST: Saches_63135935/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSach,MaLoaiSach,TenSach,AnhSach,DonGia,TacGia,NhaXuatBan,Mota,NgayXuatBan")] Sach sach)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sach).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiSach = new SelectList(db.LoaiSaches, "MaLoaiSach", "TenLoaiSach", sach.MaLoaiSach);
            return View(sach);
        }

        // GET: Saches_63135935/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // POST: Saches_63135935/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Sach sach = db.Saches.Find(id);
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_63135935/Project_63135935/Views/Saches_63135935/Aboutus.cshtml
@model IEnumerable<Project_63135935.Models.NhanVien>

@{
    ViewBag.Title = "Aboutus";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
    var chucvu = "";
}

<!--************************************
        Inner Banner Start
*************************************-->
<div class="tg-innerbanner tg-haslayout tg-parallax tg-bginnerbanner" data-z-index="-100" data-appear-top-offset="600" data-parallax="scroll" data-image-src="/Images/bgparallax-05.jpg">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="tg-innerbannercontent">
                    <h1>About Us</h1>
                    <ol class="tg-breadcrumb">
                        <li><a href="javascript:void(0);">home</a></li>
                        <li class="tg-active">About Us</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
<!--************************************
        Inner Banner End
*************************************-->
<!--************************************
        Main Start
*************************************-->
<main id="tg-main" class="tg-main tg-haslayout">
    <!--************************************
            Success Start
    *************************************-->
    <section class="tg-sectionspace tg-haslayout">
        <div class="container">
            <div class="row">
                <div class="tg-successstory">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="tg-sectionhead">
                            <h2><span>Our Pride Moments</span>Journey of Success</h2>
                        </div>
                        <div id="tg-successslider" class="tg-successslider tg-success owl-carousel">
                            <div class="item">
                                <figure>
                                    <img src="~/Images/img-01.jpg" alt="image description">
                                </figure>
                                <div class="tg-successcontent">
                                    <div class="tg-sectionhead">
                                        <h2><span>June 27, 2017</span>First Step Toward Success</h2>
                                    </div>
                                    <div class="tg-description">
                                        <p>Consectetur adipisicing elit sed do eiusmod tempor incididunt labore toloregna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamcoiars nisiuip commodo consequat aute irure dolor in aprehenderit aveli esseati cillum dolor fugiat nulla pariatur cepteur sint occaecat cupidatat.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--************************************
            Success End
    *************************************-->
    <!--************************************
            Authors Start
    *************************************-->
    <section class="tg-sectionspace tg-haslayout">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="tg-sectionhead">
                        <h2><span>Team Behind Book Library</span>Meet Our Professionals</h2>
                    </div>
                </div>
                
                <div id="tg-teamsslider" class="tg-authors tg-authorsslider tg-teamsmember owl-carousel">
                    @foreach (var item in Model)
                    {
                        <div class="item tg-author tg-member">
                            <figure><a href="javascript:void(0);"><img src="~/Images/employee.png" alt="image description"></a></figure>
                            <div class="tg-authorcontent">
                                <h2><a href="javascript:void(0);">@item.HoNV @item.TenNV</a></h2>
                                <span>
                                    @{if (item.Chucvu.tenchucvu == "admin")
                                        { chucvu = "Người Quản Lí"; }
                                        else
                                        { chucvu = "Shipper"; }
                                    }
                                    @chucvu
                                </span>
                                <ul class="tg-socialicons">
                                    <li class="tg-facebook"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
                                    <li class="tg-twitter"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
                                    <li class="tg-linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
    <!--************************************
            Authors End
    *************************************-->
</main>
<!--************************************
        Main End
*************************************-->

 

Project_63135935/Project_63135935/Views/Saches_63135935/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}



    <!--************************************
            Inner Banner Start
    *************************************-->
    <div class="tg-innerbanner tg-haslayout tg-parallax tg-bginnerbanner" data-z-index="-100" data-appear-top-offset="600" data-parallax="scroll" data-image-src="/Images/bgparallax-07.jpg">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="tg-innerbannercontent">
                        <h1>Contact Us</h1>
                        <ol class="tg-breadcrumb">
                            <li><a href="javascript:void(0);">home</a></li>
                            <li class="tg-active">Contact Us</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--************************************
            Inner Banner End
    *************************************-->
    <!--************************************
            Main Start
    *************************************-->
    <main id="tg-main" class="tg-main tg-haslayout">
        <!--************************************
                Contact Us Start
        *************************************-->
        <div class="tg-sectionspace tg-haslayout">
            <div class="container">
                <div class="row">
                    <div class="tg-contactus">
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="tg-sectionhead">
                                <h2><span>Say Hello!</span>Get In Touch With Us</h2>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div id="tg-locationmap" class="tg-locationmap tg-map" style="height: 360px"></div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="tg-contactdetail">
                                <div class="tg-sectionhead">
                                    <h2>Get In Touch With Us</h2>
                                </div>
                                <ul class="tg-contactinfo">
                                    <li>
                                        <i class="icon-apartment"></i>
                                        <address>Suit # 07, Rose world Building, Street # 02, AT246T Manchester</address>
                                    </li>
                                    <li>
                                        <i class="icon-phone-handset"></i>
                                        <span>
                                            <em>0800 12345 - 678 - 89</em>
                                            <em>+4 1234 - 4567 - 67</em>
                                        </span>
                                    </li>
                                    <li>
                                        <i class="icon-clock"></i>
                                        <span>Serving 7 Days A Week From 9am - 5pm</span>
                                    </li>
                                    <li>
                                        <i class="icon-envelope"></i>
                                        <span>
                                            <em><a href="mailto:support@domain.com">support@domain.com</a></em>
                                            <em><a href="mailto:info@domain.com">info@domain.com</a></em>
                                        </span>
                                    </li>
                                </ul>
                                <ul class="tg-socialicons">
                                    <li class="tg-facebook"><a href="javascript:void(0);"><i class="fa fa-facebook"></i></a></li>
                                    <li class="tg-twitter"><a href="javascript:void(0);"><i class="fa fa-twitter"></i></a></li>
                                    <li class="tg-linkedin"><a href="javascript:void(0);"><i class="fa fa-linkedin"></i></a></li>
                                    <li class="tg-googleplus"><a href="javascript:void(0);"><i class="fa fa-google-plus"></i></a></li>
                                    <li class="tg-rss"><a href="javascript:void(0);"><i class="fa fa-rss"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--************************************
                Contact Us End
        *************************************-->
    </main>
    <!--************************************
            Main End
    *************************************-->


<!--************************************
        Wrapper End
*************************************-->

Project_63135935/Project_63135935/Views/Saches_63135935/Create.cshtml
@model Project_63135935.Models.Sach

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSach, "MaLoaiSach", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSach", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TacGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhaXuatBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NhaXuatBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NhaXuatBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayXuatBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayXuatBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayXuatBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project_63135935/Project_63135935/Views/Saches_63135935/Details.cshtml
@model Project_63135935.Models.Sach

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}


    <head>
        <style>
            .btn-event a {
                color: white;
                padding: 6px 12px;
                margin: 0px 5px;
                background-color: #4e73df;
            }

            tr td {
                border: none !important;
            }

            tr td {
                text-align: left !important;
            }
        </style>
    </head>


<body>
    <div class="container my-5" style="clear:both; padding: 20px 0px">

        <div style="font-size:18px; align-items: center" class="d-sm-block d-md-flex">
            <div class="p-3 col-md-3">
                <img src="/Images/@Html.DisplayFor(model => model.AnhSach)" style="max-height: 300px" />
            </div>
            <div>
                <table cellpadding="10" style="border: none !important" class="col-xs-12 col-sm-12 col-md-9">
                    <tr>
                        <td>Tên Sách: </td>
                        <td>@Html.DisplayFor(model => model.TenSach)</td>
                    </tr>
                    <tr>
                        <td>Thể Loại: </td>
                        <td>@Html.DisplayFor(model => model.LoaiSach.TenLoaiSach)</td>
                    </tr>
                    <tr>
                        <td>Tên Tác Giả: </td>
                        
                        <td>@Html.DisplayFor(model => model.TacGia)</td>
                    </tr>
                    <tr>
                        <td>Nhà Xuất Bản:</td>
                        <td> @Html.DisplayFor(model => model.NhaXuatBan)</td>
                    </tr>
                    <tr>
                        <td>Ngày Xuất Bản: </td>
                        <td>@Html.DisplayFor(model => model.NgayXuatBan)</td>
                    </tr>
                    <tr>
                        <td>Tóm Tắt:</td>
                        <td> @Html.DisplayFor(model => model.Mota)</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="my-4 d-block btn-event d-flex" style=" margin-top: 20px 0px;">
            <a class="tg-btn tg-btnstyletwo" href="@Url.Action("Create", "GioHangs_63135935", new { tensach = Model.TenSach, idsach = Model.MaSach })">
                <i class="fa fa-shopping-basket"></i>
                <em>Mua Hàng</em>
            </a>
            <a class="tg-btn tg-btnstyletwo" href="@Url.Action("index", "Saches_63135935")">
                <em>Quay Lại</em>
            </a>
        </div>
    </div>
</body>

Project_63135935/Project_63135935/Views/Saches_63135935/Index.cshtml
@model IEnumerable<Project_63135935.Models.Sach>

@{
    ViewBag.Title = Model;
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}


<section class="tg-sectionspace tg-haslayout">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="tg-sectionhead">
                    <h2><span>People’s Choice</span>Books</h2>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" >
                @foreach (var item in Model)
                {
                    var link = "/Saches_63135935/Details/" + item.MaSach;

                    <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12" style="height: 600px">
                        <div class="tg-postbook">
                            <figure class="tg-featureimg">
                                <div class="tg-bookimg">
                                    <div class="tg-frontcover"><a href="@link"><img src="~/Images/@item.AnhSach" alt="image description" style="height: 300px"></a></div>
                                    <div class="tg-backcover"><a href="@link"><img src="~/Images/@item.AnhSach" alt="image description" style="height: 300px"></a></div>
                                </div>
                            </figure>
                            <div class="tg-postbookcontent">
                                <ul class="tg-bookscategories">
                                    <li>@item.LoaiSach.TenLoaiSach</li>
                                </ul>
                                <div class="tg-booktitle">
                                    <h3><a href="@link">@item.TenSach</a></h3>
                                </div>
                                <span class="tg-bookwriter">By: <a href="#">@item.TacGia</a></span>
                                <span class="tg-stars"><span></span></span>
                                <span class="tg-bookprice">
                                    <ins>@item.DonGia</ins>
                                </span>
                                <a class="tg-btn tg-btnstyletwo" href="@Url.Action("Create", "GioHangs_63135935", new { tensach = item.TenSach, idsach = item.MaSach })">
                                    <i class="fa fa-shopping-basket"></i>
                                    <em>Mua hàng</em>
                                </a>
                            </div>
                        </div>
                    </div>


                }

            </div>
        </div>
    </div>
</section>