Project_63135935/Project_63135935/Areas/Admin/Controllers/Login_63135935Controller.cs
using Project_63135935.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Project_63135935.Areas.Admin.Controllers
{
    public class Login_63135935Controller : Controller
    {
        // GET: Admin/Login_63135935
        private Project_63135935Entities1 db = new Project_63135935Entities1();

        string LayMaKh()
        {
            var maMax = db.KhachHangs.Select(n => n.MaKH).OrderByDescending(ma => ma).FirstOrDefault();

            if (maMax != null)
            {
                int maSach = int.Parse(maMax.Substring(3)) + 1;
                string newMaSach = "MKH" + maSach.ToString("000");
                return newMaSach;
            }

            return "MKH001";
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string username, string password)
        {
            var loginSingle = db.NhanViens.SqlQuery("SELECT * FROM NhanVien WHERE Email='" + username + "' AND Matkhau = '" + password + "'").SingleOrDefault();
            if (loginSingle == null)
            {
                ViewBag.error = "Email đăng Nhập hoặc mật khẩu của bạn không đúng";
                return View();
            }
            else
            {
                return RedirectToAction("Index", "AdminSaches_63135935");
            }
        }

        [HttpGet]
        public ActionResult Register()
        {
            ViewBag.MaKh = LayMaKh();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "MaKH,HoKH,TenKH,DiaChi,SoDT,NgaySinh,GioiTinh,Email,Matkhau")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                khachHang.MaKH = LayMaKh();
                db.KhachHangs.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.error = "tài khoản có một số thông tin này đã được sử dụng";
            return View();
        }
    }
}

Project_63135935/Project_63135935/Controllers/Saches_63135935Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63135935.Models;

namespace Project_63135935.Controllers
{
    public class Saches_63135935Controller : Controller
    {
        private Project_63135935Entities1 db = new Project_63135935Entities1();

        // GET: Saches_63135935

        public ActionResult ShowBooksByCategory(string idcategory)
        {
            var bookincategory = db.Saches.SqlQuery("SELECT * FROM Sach WHERE MaLoaiSach='" + idcategory + "'");
            return View(bookincategory.ToList());
        }

        public ActionResult Aboutus()
        {
            var nhanviens = db.NhanViens.Include(n => n.Chucvu);
            return View(nhanviens);
        }

        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult Index()
        {
            var saches = db.Saches.Include(s => s.LoaiSach);
            return View(saches.ToList());
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            var saches = db.Saches.Where(s => s.TenSach.Contains(search)).ToList();
            return View(saches);
        }

        // GET: Saches_63135935/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // GET: Saches_63135935/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSach = new SelectList(db.LoaiSaches, "MaLoaiSach", "TenLoaiSach");
            return View();
        }

        // POST: Saches_63135935/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSach,MaLoaiSach,TenSach,AnhSach,DonGia,TacGia,NhaXuatBan,Mota,NgayXuatBan")] Sach sach)
        {
            if (ModelState.IsValid)
            {
                db.Saches.Add(sach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLoaiSach = new SelectList(db.LoaiSaches, "MaLoaiSach", "TenLoaiSach", sach.MaLoaiSach);
            return View(sach);
        }

        // GET: Saches_63135935/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSach = new SelectList(db.LoaiSaches, "MaLoaiSach", "TenLoaiSach", sach.MaLoaiSach);
            return View(sach);
        }

        // POST: Saches_63135935/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSach,MaLoaiSach,TenSach,AnhSach,DonGia,TacGia,NhaXuatBan,Mota,NgayXuatBan")] Sach sach)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sach).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiSach = new SelectList(db.LoaiSaches, "MaLoaiSach", "TenLoaiSach", sach.MaLoaiSach);
            return View(sach);
        }

        // GET: Saches_63135935/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // POST: Saches_63135935/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Sach sach = db.Saches.Find(id);
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_63135935/Project_63135935/Areas/Admin/Views/Login_63135935/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/Style_Admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/Style_Admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9 d-flex justify-content-center">

                <div class="card o-hidden border-0 shadow-lg my-5 col-8">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                        <h6 style="color: red">@ViewBag.error</h6>
                                    </div>
                                    @using (Html.BeginForm("Index", "Login_63135935", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                   id="exampleInputEmail" name="username" aria-describedby="emailHelp"
                                                   placeholder="Enter Email Address...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                   id="exampleInputPassword" name="password" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">
                                                    Remember
                                                    Me
                                                </label>
                                            </div>
                                        </div>
                                        <input value="Login" type="submit" class="btn btn-primary btn-user btn-block" />
                                    }
                                    <hr>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("Register", "Login_63135935") ">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("Index", "Saches_63135935", new { area = "" }) ">Về Trang Chủ</a>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/Style_Admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/Style_Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/Style_Admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/Style_Admin/js/sb-admin-2.min.js"></script>

</body>

</html>

Project_63135935/Project_63135935/Areas/Admin/Views/Login_63135935/Register.cshtml
@model Project_63135935.Models.KhachHang

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Register</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/Style_Admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/Style_Admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container d-flex justify-content-center">

        <div class="card o-hidden border-0 shadow-lg my-5 col-md-8">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                                <h6 style="color: red">@ViewBag.error</h6>
                            </div>
                            @using (Html.BeginForm("Register", "Login_63135935", FormMethod.Post, new { enctype = "multipart/form-data", @class = "user" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        @Html.EditorFor(model => model.HoKH, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Họ Người Dùng" } })
                                        @Html.ValidationMessageFor(model => model.HoKH, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-6">
                                        @Html.EditorFor(model => model.TenKH, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Tên Người Dùng" } })
                                        @Html.ValidationMessageFor(model => model.TenKH, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group d-flex">
                                    @Html.LabelFor(model => model.GioiTinh, "Giới Tính:", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                                            Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                                            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                                        </div>

                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control form-control-user", @type = "email", placeholder = "Email Đăng Nhập" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Địa Chỉ" } })
                                    @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        @Html.EditorFor(model => model.SoDT, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Số Điện Thoại" } })
                                        @Html.ValidationMessageFor(model => model.SoDT, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-sm-6">
                                        @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control form-control-user", placeholder = "Ngày Sinh", @type = "date"} })
                                        @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.EditorFor(model => model.Matkhau, new { htmlAttributes = new { @class = "form-control form-control-user", @type = "password", placeholder = "Mật Khẩu" } })
                                    @Html.ValidationMessageFor(model => model.Matkhau, "", new { @class = "text-danger" })
                                </div>
                                <input value="Register Account" type="submit" class="btn btn-primary btn-user btn-block" />
                                <hr>
                            }

                            <hr>
                            <div class="text-center">
                                <a class="small" href="@Url.Action("Index", "Login_63135935")">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/Style_Admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/Style_Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/Style_Admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/Style_Admin/js/sb-admin-2.min.js"></script>

</body>

</html>