Project_63135935/Project_63135935/Areas/Admin/Controllers/AdminChiTietGioHangs_63135935Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63135935.Models;

namespace Project_63135935.Areas.Admin.Controllers
{
    public class AdminChiTietGioHangs_63135935Controller : Controller
    {
        private Project_63135935Entities1 db = new Project_63135935Entities1();

        // GET: Admin/AdminChiTietGioHangs_63135935
        public ActionResult Index()
        {
            var chiTietGioHangs = db.ChiTietGioHangs.Include(c => c.Sach).Include(c => c.GioHang);
            return View(chiTietGioHangs.ToList());
        }

        // GET: Admin/AdminChiTietGioHangs_63135935/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietGioHang chiTietGioHang = db.ChiTietGioHangs.Find(id);
            if (chiTietGioHang == null)
            {
                return HttpNotFound();
            }
            return View(chiTietGioHang);
        }

        // GET: Admin/AdminChiTietGioHangs_63135935/Create
        public ActionResult Create()
        {
            ViewBag.MaSach = new SelectList(db.Saches, "MaSach", "MaLoaiSach");
            ViewBag.MaDH = new SelectList(db.GioHangs, "MaDH", "MaKH");
            return View();
        }

        // POST: Admin/AdminChiTietGioHangs_63135935/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDH,MaSach,SoLuong,ThanhTien,GiaBan")] ChiTietGioHang chiTietGioHang)
        {
            if (ModelState.IsValid)
            {
                db.ChiTietGioHangs.Add(chiTietGioHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaSach = new SelectList(db.Saches, "MaSach", "MaLoaiSach", chiTietGioHang.MaSach);
            ViewBag.MaDH = new SelectList(db.GioHangs, "MaDH", "MaKH", chiTietGioHang.MaDH);
            return View(chiTietGioHang);
        }

        // GET: Admin/AdminChiTietGioHangs_63135935/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietGioHang chiTietGioHang = db.ChiTietGioHangs.Find(id);
            if (chiTietGioHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaSach = new SelectList(db.Saches, "MaSach", "MaLoaiSach", chiTietGioHang.MaSach);
            ViewBag.MaDH = new SelectList(db.GioHangs, "MaDH", "MaKH", chiTietGioHang.MaDH);
            return View(chiTietGioHang);
        }

        // POST: Admin/AdminChiTietGioHangs_63135935/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDH,MaSach,SoLuong,ThanhTien,GiaBan")] ChiTietGioHang chiTietGioHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chiTietGioHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaSach = new SelectList(db.Saches, "MaSach", "MaLoaiSach", chiTietGioHang.MaSach);
            ViewBag.MaDH = new SelectList(db.GioHangs, "MaDH", "MaKH", chiTietGioHang.MaDH);
            return View(chiTietGioHang);
        }

        // GET: Admin/AdminChiTietGioHangs_63135935/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietGioHang chiTietGioHang = db.ChiTietGioHangs.Find(id);
            if (chiTietGioHang == null)
            {
                return HttpNotFound();
            }
            return View(chiTietGioHang);
        }

        // POST: Admin/AdminChiTietGioHangs_63135935/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ChiTietGioHang chiTietGioHang = db.ChiTietGioHangs.Find(id);
            db.ChiTietGioHangs.Remove(chiTietGioHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_63135935/Project_63135935/Areas/Admin/Controllers/AdminGioHangs_63135935Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63135935.Models;

namespace Project_63135935.Areas.Admin.Controllers
{
    public class AdminGioHangs_63135935Controller : Controller
    {
        private Project_63135935Entities1 db = new Project_63135935Entities1();

        // GET: Admin/AdminGioHangs_63135935
        public ActionResult Index()
        {
            var gioHangs = db.GioHangs.Include(g => g.KhachHang).Include(g => g.NhanVien);
            return View(gioHangs.ToList());
        }

        // GET: Admin/AdminGioHangs_63135935/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GioHang gioHang = db.GioHangs.Find(id);
            if (gioHang == null)
            {
                return HttpNotFound();
            }
            return View(gioHang);
        }

        // GET: Admin/AdminGioHangs_63135935/Create
        public ActionResult Create()
        {
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoKH");
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "HoNV");
            return View();
        }

        // POST: Admin/AdminGioHangs_63135935/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDH,NgayDat,MaKH,MaNV,Sodt,Diachigiaohang,Email,DuyetDH")] GioHang gioHang)
        {
            if (ModelState.IsValid)
            {
                db.GioHangs.Add(gioHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoKH", gioHang.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "HoNV", gioHang.MaNV);
            return View(gioHang);
        }

        // GET: Admin/AdminGioHangs_63135935/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GioHang gioHang = db.GioHangs.Find(id);
            if (gioHang == null)
            {
                return HttpNotFound();
            }

            var khachHangs = db.KhachHangs.ToList();
            var nhanViens = db.NhanViens.ToList();

            ViewBag.MaKH = new SelectList(khachHangs.Select(kh => new SelectListItem
            {
                Text = kh.HoKH + " " + kh.TenKH,
                Value = kh.MaKH.ToString()
            }), "Value", "Text", gioHang.MaKH);

            ViewBag.MaNV = new SelectList(nhanViens.Select(nv => new SelectListItem
            {
                Text = nv.HoNV + " " + nv.TenNV,
                Value = nv.MaNV.ToString()
            }), "Value", "Text", gioHang.MaNV);

            return View(gioHang);
        }

        // POST: Admin/AdminGioHangs_63135935/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDH,NgayDat,MaKH,MaNV,Sodt,Diachigiaohang,Email,DuyetDH")] GioHang gioHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gioHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "AdminChiTietGioHangs_63135935");
            }
            ViewBag.MaKH = new SelectList(db.KhachHangs, "MaKH", "HoKH", gioHang.MaKH);
            ViewBag.MaNV = new SelectList(db.NhanViens, "MaNV", "HoNV", gioHang.MaNV);

            return View(gioHang);
        }

        // GET: Admin/AdminGioHangs_63135935/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GioHang gioHang = db.GioHangs.Find(id);
            if (gioHang == null)
            {
                return HttpNotFound();
            }
            return View(gioHang);
        }

        // POST: Admin/AdminGioHangs_63135935/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            GioHang gioHang = db.GioHangs.Find(id);
            db.GioHangs.Remove(gioHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_63135935/Project_63135935/Areas/Admin/Views/AdminChiTietGioHangs_63135935/Create.cshtml
@model Project_63135935.Models.ChiTietGioHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChiTietGioHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaDH, "MaDH", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaDH", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaSach, "MaSach", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaSach", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThanhTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThanhTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThanhTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_63135935/Project_63135935/Areas/Admin/Views/AdminChiTietGioHangs_63135935/Delete.cshtml
@model Project_63135935.Models.ChiTietGioHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ChiTietGioHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThanhTien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThanhTien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sach.MaLoaiSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sach.MaLoaiSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioHang.MaKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioHang.MaKH)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project_63135935/Project_63135935/Areas/Admin/Views/AdminChiTietGioHangs_63135935/Details.cshtml
@model Project_63135935.Models.ChiTietGioHang

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    p a {
        color: white;
        padding: 6px 12px;
        margin: 0px 5px;
        background-color: #4e73df;
    }
</style>

<div class="container-fluid">
    <h3 class="my-4 text-center">THÔNG TIN CHI TIẾT</h3>

    <div style="font-size:18px; align-items: center" class="d-sm-block d-md-flex">
        <div>
            <table cellpadding="10">
                <tr>
                    <th>
                        <h4>Thông tin khách hàng đặt</h4>
                    </th>
                </tr>
                <tr>
                    <td>Tên Khách Hàng:</td>
                    <td>
                        @Html.DisplayFor(model => model.GioHang.KhachHang.HoKH)
                        @Html.DisplayFor(model => model.GioHang.KhachHang.TenKH)
                    </td>
                <tr>
                    <td>Địa Chỉ giao hàng:</td>
                    <td>@Html.DisplayFor(model => model.GioHang.Diachigiaohang)</td>
                </tr>
                <tr>
                    <td>Số Điện Thoại:</td>
                    <td>@Html.DisplayFor(model => model.GioHang.Sodt)</td>
                </tr>
                <tr>
                    <td>Email:</td>
                    <td>@Html.DisplayFor(model => model.GioHang.Email)</td>
                </tr>
                <tr>
                    <th>
                        <h4>Thông tin nhân viên shipper</h4>
                    </th>
                </tr>
                <tr>
                    <td>Tên Shipper:</td>
                    <td>@Html.DisplayFor(model => model.GioHang.NhanVien.TenNV)</td>
                </tr>
                <tr>
                    <th>
                        <h4>Thông tin sản phẩm được đặt</h4>
                    </th>
                </tr>
                <tr>
                    <td>Tên Sản Phẩm:</td>
                    <td>@Html.DisplayFor(model => model.Sach.TenSach)</td>
                </tr>
                <tr>
                    <td>Thể Loại:</td>
                    <td>@Html.DisplayFor(model => model.Sach.LoaiSach.TenLoaiSach)</td>
                </tr>
                <tr>
                    <td>ngày đặt hàng:</td>
                    <td>@Html.DisplayFor(model => model.GioHang.NgayDat)</td>
                </tr>
                <tr>
                    <td>Số lượng:</td>
                    <td>@Html.DisplayFor(model => model.SoLuong)</td>
                </tr>
                <tr>
                    <td>Tổng tiền:</td>
                    <td>@Html.DisplayFor(model => model.ThanhTien)</td>
                </tr>
            </table>
        </div>
    </div>
    <p class="my-4 d-sm-flex justify-content-center">
        @Html.ActionLink("Quay lại", "Index")
    </p>
</div>

Project_63135935/Project_63135935/Areas/Admin/Views/AdminChiTietGioHangs_63135935/Edit.cshtml
@model Project_63135935.Models.ChiTietGioHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChiTietGioHang</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDH)

        @Html.HiddenFor(model => model.MaSach)

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThanhTien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThanhTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThanhTien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project_63135935/Project_63135935/Areas/Admin/Views/AdminChiTietGioHangs_63135935/Index.cshtml
@model IEnumerable<Project_63135935.Models.ChiTietGioHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "DuyetDH", rowsPerPage: 10);
}

<head>
    <style>
        .btn_create {
            display: inline-block;
            max-width: 200px;
            background-color: lightskyblue;
            padding: 5px 10px;
            cursor: pointer;
        }

            .btn_create a {
                color: #4e73df !important;
                text-decoration: none;
            }

                .btn_create a:hover {
                    color: white !important;
                }

        a:hover, a {
            text-decoration: none !important;
        }

        form {
            display: flex !important;
            align-items: center;
            justify-content: center;
        }

        .btn-event {
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 10px 0px 20px 0px;
        }

        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue !important;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    color: #FFAD33;
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        table td:last-child a{
            margin: 0px 5px;
        }

        table td:last-child a:first-child{
            margin-right: 0px !important;
        }

        table td {
            text-align: center;
        }

        th a {
            color: dodgerblue !important;
        }

        th {
            text-align: center;
        }

        .gridContent abbr[data-original-title], abbr[title] {
            cursor: pointer !important;
        }
    </style>
</head>

<body>

    <div class="container-fluid">
        <h2 style="text-align: center">DANH SÁCH ĐƠN HÀNG</h2>

        <div id="gridContent">
            @ViewBag.TB
            @grid.GetHtml(
                tableStyle: "table table-bordered table-hover",
                footerStyle: "grid-footer",
                fillEmptyRows: true,
                mode: WebGridPagerModes.Numeric,
                alternatingRowStyle: "alternatingRowStyle",
                  columns: new[]  // colums in grid
                 {
            grid.Column("GioHang.MaDH","Mã Đơn Hàng"), //the model fields to display
            grid.Column("GioHang.KhachHang.HoKH","Họ Khách Hàng"  ),
            grid.Column("GioHang.KhachHang.TenKH","Tên Khách Hàng"),
            grid.Column("Sach.TenSach","Sản Phẩm được mua"),
            grid.Column("Sach.AnhSach", "Ảnh Sách" ,format: (item) => new HtmlString($"<img src='/Images/{item.Sach.AnhSach}' width='100' />")),
            grid.Column("SoLuong", "Số Lượng"),
            grid.Column("ThanhTien", "Tổng Tiền"),
            grid.Column("GioHang.DuyetDH","Thanh Toán",format: (@item) => @item.GioHang.DuyetDH==true?"Rồi":"chưa"),
            grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit", "AdminGioHangs_63135935",
                    new { id = item.MaDH})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Details",
                    new { id = item.MaCTGH})" class="edit-btn"><abbr title="Xem thông tin chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
                @using (Html.BeginForm("", "AdminChiTietGioHangs_63135935", FormMethod.Post, new {@class = "form-inline", id = item.MaDH}))
                {
                    @Html.AntiForgeryToken()
                        <input type="submit" value="" class="btn btn-default" style="background-image: url(/Images/yes.png); width: 20px; height: 20px; background-size: contain; background-repeat: no-repeat"/>
                }
            </text>),

}
)
        </div>
    </div>

</body>